server:
  port: 8082

spring:
  application:
    name: "inventory-service"
  datasource:
    url: jdbc:mysql://localhost:3308/inventory_service
    username: inventory_service
    password: inventory_service
  jpa:
    hibernate:
      ddl-auto: none